### PR TITLE
Fix PHP 8.1 deprecation warnings on Helper and FormHelper

### PR DESCRIPTION
**Pull request by diegosurita**
- fix deprecation warning when Helper::_entityPath is null
- fix `strftime` function deprecation warning on FormHelper::_getDateTimeValue method

### CODE REVIEW

**Comment by diegosurita** [comment]
Hi @kamilwylegala, could you review and merge it, please?

**Comment by diegosurita** [comment]
I'm going to create another PR soon.

**Comment by kamilwylegala** [comment]
Any reason why this one got closed?

**Comment by diegosurita** [comment]
I'm going to create the PR from another fork

**Pull request closed without merging**
