### PR TITLE
solving the named parameters incompatibility

### PR DESCRIPTION
**Pull request by impronta48**
There was a problem on event dispatch, complaining about named parameters

### CODE REVIEW

**Comment by kamilwylegala** [comment]
@impronta48 Thank you for your contribution. For some reason, tests are failing. I will double-check what's going on during the week (hopefully).

**Comment by tenkoma** [comment]
```
There was 1 error:

1) RedisEngineTest::testClear
Error: Call to undefined method Redis::getKeys()

/home/runner/work/cakephp2-php8/cakephp2-php8/lib/Cake/Cache/Engine/RedisEngine.php:190
/home/runner/work/cakephp2-php8/cakephp2-php8/lib/Cake/Cache/Cache.php:469
/home/runner/work/cakephp2-php8/cakephp2-php8/lib/Cake/Test/Case/Cache/Engine/RedisEngineTest.php:313
```

This test failure may have started to occur with the removal of `Redis::getKeys()` in PhpRedis 6.0.0, released in September 2023.

https://github.com/phpredis/phpredis/commit/de985150cf35b04f185ca00029ef8ae7b32c8562#diff-a1471159ac00556a439382b010c89a8507ebc6f03311ec7655cebd95dc6c978eL462-L466
```diff
-     /* Mark all of these aliases deprecated.  They aren't actual Redis commands. */
-      PHP_MALIAS(Redis, delete, del, arginfo_del, ZEND_ACC_PUBLIC | ZEND_ACC_DEPRECATED)
-      PHP_MALIAS(Redis, evaluate, eval, arginfo_eval, ZEND_ACC_PUBLIC | ZEND_ACC_DEPRECATED)
-      PHP_MALIAS(Redis, evaluateSha, evalsha, arginfo_evalsha, ZEND_ACC_PUBLIC | ZEND_ACC_DEPRECATED)
-      PHP_MALIAS(Redis, getKeys, keys, arginfo_keys, ZEND_ACC_PUBLIC | ZEND_ACC_DEPRECATED)
```

**Comment by kamilwylegala** [comment]
@impronta48 Could you rebase your changes over `master`. I fixed `getKeys`  issue, after that tests should be green.

**Comment by impronta48** [comment]
I've rebased master. Would be great if you could merge my data.
Thanks
Massimo

**Pull request merged**
